/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Auditor' : null } |
  { 'Admin' : null } |
  { 'Manager' : null } |
  { 'Salesman' : null };
export interface CreditNote {
  'id' : string,
  'linkedInvoiceId' : string,
  'date' : Time,
  'amount' : number,
  'partyId' : string,
  'reason' : string,
}
export interface DebitNote {
  'id' : string,
  'date' : Time,
  'linkedBillId' : string,
  'amount' : number,
  'partyId' : string,
  'reason' : string,
}
export interface Expense {
  'id' : string,
  'date' : Time,
  'createdBy' : string,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface InvoiceTemplate {
  'id' : string,
  'name' : string,
  'isDefault' : boolean,
  'printSize' : { 'a4' : null } |
    { 'a5' : null } |
    { 'thermal' : null },
  'layoutConfig' : string,
}
export interface POSSession {
  'id' : string,
  'status' : string,
  'cashierId' : string,
  'date' : Time,
  'openingCash' : number,
  'totalSales' : number,
  'closingCash' : number,
}
export interface Party {
  'id' : string,
  'currentBalance' : number,
  'kind' : { 'customer' : null } |
    { 'vendor' : null },
  'name' : string,
  'email' : string,
  'address' : string,
  'openingBalance' : number,
  'phone' : string,
}
export interface Product {
  'id' : string,
  'sku' : string,
  'purchasePrice' : number,
  'lowStockThreshold' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'unit' : string,
  'isActive' : boolean,
  'category' : string,
  'salePrice' : number,
}
export interface PurchaseBill {
  'id' : string,
  'tax' : number,
  'status' : string,
  'total' : number,
  'date' : Time,
  'billNumber' : string,
  'paymentMode' : string,
  'items' : Array<SaleInvoiceItem>,
  'paidAmount' : number,
  'partyId' : string,
  'subtotal' : number,
}
export interface SaleInvoice {
  'id' : string,
  'tax' : number,
  'status' : string,
  'total' : number,
  'date' : Time,
  'createdBy' : string,
  'invoiceNumber' : string,
  'paymentMode' : string,
  'items' : Array<SaleInvoiceItem>,
  'paidAmount' : number,
  'partyId' : string,
  'subtotal' : number,
}
export interface SaleInvoiceItem {
  'qty' : bigint,
  'productId' : string,
  'discount' : number,
  'price' : number,
}
export type Time = bigint;
export interface UserProfile { 'appRole' : AppRole, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearData' : ActorMethod<[], undefined>,
  'closePOSSession' : ActorMethod<[string, number], undefined>,
  'createCreditNote' : ActorMethod<[CreditNote], undefined>,
  'createDebitNote' : ActorMethod<[DebitNote], undefined>,
  'createExpense' : ActorMethod<[Expense], undefined>,
  'createInvoiceTemplate' : ActorMethod<[InvoiceTemplate], undefined>,
  'createParty' : ActorMethod<[Party], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'createPurchaseBill' : ActorMethod<[PurchaseBill], undefined>,
  'createSaleInvoice' : ActorMethod<[SaleInvoice], undefined>,
  'deleteParty' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentPOSSession' : ActorMethod<[], [] | [POSSession]>,
  'getDailySalesSummary' : ActorMethod<
    [Time],
    { 'invoiceCount' : bigint, 'totalSales' : number }
  >,
  'getDefaultTemplate' : ActorMethod<[], [] | [InvoiceTemplate]>,
  'getExpenseSummary' : ActorMethod<
    [Time, Time],
    Array<{ 'total' : number, 'category' : string }>
  >,
  'getInventoryReport' : ActorMethod<
    [],
    Array<{ 'value' : number, 'product' : Product }>
  >,
  'getParty' : ActorMethod<[string], [] | [Party]>,
  'getPartyLedger' : ActorMethod<
    [string],
    {
      'invoices' : Array<SaleInvoice>,
      'bills' : Array<PurchaseBill>,
      'party' : [] | [Party],
    }
  >,
  'getProduct' : ActorMethod<[string], Product>,
  'getProfitLoss' : ActorMethod<
    [Time, Time],
    {
      'revenue' : number,
      'cost' : number,
      'expenses' : number,
      'profit' : number,
    }
  >,
  'getPurchaseBill' : ActorMethod<[string], [] | [PurchaseBill]>,
  'getSaleInvoice' : ActorMethod<[string], SaleInvoice>,
  'getSalesSummary' : ActorMethod<
    [Time, Time],
    { 'invoiceCount' : bigint, 'totalSales' : number }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCreditNotes' : ActorMethod<[], Array<CreditNote>>,
  'listDebitNotes' : ActorMethod<[], Array<DebitNote>>,
  'listExpenses' : ActorMethod<[], Array<Expense>>,
  'listExpensesByCategory' : ActorMethod<[string], Array<Expense>>,
  'listInvoiceTemplates' : ActorMethod<[], Array<InvoiceTemplate>>,
  'listParties' : ActorMethod<[], Array<Party>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listPurchaseBills' : ActorMethod<[], Array<PurchaseBill>>,
  'listPurchaseBillsByParty' : ActorMethod<[string], Array<PurchaseBill>>,
  'listSaleInvoices' : ActorMethod<[], Array<SaleInvoice>>,
  'listSaleInvoicesByParty' : ActorMethod<[string], Array<SaleInvoice>>,
  'openPOSSession' : ActorMethod<[POSSession], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDefaultTemplate' : ActorMethod<[string], undefined>,
  'updateBalance' : ActorMethod<[string, number], undefined>,
  'updateInvoiceTemplate' : ActorMethod<[InvoiceTemplate], undefined>,
  'updateParty' : ActorMethod<[Party], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updatePurchaseBill' : ActorMethod<[PurchaseBill], undefined>,
  'updateSaleInvoice' : ActorMethod<[SaleInvoice], undefined>,
  'updateStock' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];