/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CreditNote = IDL.Record({
  'id' : IDL.Text,
  'linkedInvoiceId' : IDL.Text,
  'date' : Time,
  'amount' : IDL.Float64,
  'partyId' : IDL.Text,
  'reason' : IDL.Text,
});
export const DebitNote = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'linkedBillId' : IDL.Text,
  'amount' : IDL.Float64,
  'partyId' : IDL.Text,
  'reason' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'createdBy' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const InvoiceTemplate = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isDefault' : IDL.Bool,
  'printSize' : IDL.Variant({
    'a4' : IDL.Null,
    'a5' : IDL.Null,
    'thermal' : IDL.Null,
  }),
  'layoutConfig' : IDL.Text,
});
export const Party = IDL.Record({
  'id' : IDL.Text,
  'currentBalance' : IDL.Float64,
  'kind' : IDL.Variant({ 'customer' : IDL.Null, 'vendor' : IDL.Null }),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'openingBalance' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'purchasePrice' : IDL.Float64,
  'lowStockThreshold' : IDL.Int,
  'stockQty' : IDL.Int,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'salePrice' : IDL.Float64,
});
export const SaleInvoiceItem = IDL.Record({
  'qty' : IDL.Int,
  'productId' : IDL.Text,
  'discount' : IDL.Float64,
  'price' : IDL.Float64,
});
export const PurchaseBill = IDL.Record({
  'id' : IDL.Text,
  'tax' : IDL.Float64,
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'date' : Time,
  'billNumber' : IDL.Text,
  'paymentMode' : IDL.Text,
  'items' : IDL.Vec(SaleInvoiceItem),
  'paidAmount' : IDL.Float64,
  'partyId' : IDL.Text,
  'subtotal' : IDL.Float64,
});
export const SaleInvoice = IDL.Record({
  'id' : IDL.Text,
  'tax' : IDL.Float64,
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'date' : Time,
  'createdBy' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'paymentMode' : IDL.Text,
  'items' : IDL.Vec(SaleInvoiceItem),
  'paidAmount' : IDL.Float64,
  'partyId' : IDL.Text,
  'subtotal' : IDL.Float64,
});
export const AppRole = IDL.Variant({
  'Auditor' : IDL.Null,
  'Admin' : IDL.Null,
  'Manager' : IDL.Null,
  'Salesman' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
});
export const POSSession = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'cashierId' : IDL.Text,
  'date' : Time,
  'openingCash' : IDL.Float64,
  'totalSales' : IDL.Float64,
  'closingCash' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearData' : IDL.Func([], [], []),
  'closePOSSession' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'createCreditNote' : IDL.Func([CreditNote], [], []),
  'createDebitNote' : IDL.Func([DebitNote], [], []),
  'createExpense' : IDL.Func([Expense], [], []),
  'createInvoiceTemplate' : IDL.Func([InvoiceTemplate], [], []),
  'createParty' : IDL.Func([Party], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'createPurchaseBill' : IDL.Func([PurchaseBill], [], []),
  'createSaleInvoice' : IDL.Func([SaleInvoice], [], []),
  'deleteParty' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentPOSSession' : IDL.Func([], [IDL.Opt(POSSession)], ['query']),
  'getDailySalesSummary' : IDL.Func(
      [Time],
      [IDL.Record({ 'invoiceCount' : IDL.Nat, 'totalSales' : IDL.Float64 })],
      ['query'],
    ),
  'getDefaultTemplate' : IDL.Func([], [IDL.Opt(InvoiceTemplate)], ['query']),
  'getExpenseSummary' : IDL.Func(
      [Time, Time],
      [IDL.Vec(IDL.Record({ 'total' : IDL.Float64, 'category' : IDL.Text }))],
      ['query'],
    ),
  'getInventoryReport' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'value' : IDL.Float64, 'product' : Product }))],
      ['query'],
    ),
  'getParty' : IDL.Func([IDL.Text], [IDL.Opt(Party)], ['query']),
  'getPartyLedger' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'invoices' : IDL.Vec(SaleInvoice),
          'bills' : IDL.Vec(PurchaseBill),
          'party' : IDL.Opt(Party),
        }),
      ],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProfitLoss' : IDL.Func(
      [Time, Time],
      [
        IDL.Record({
          'revenue' : IDL.Float64,
          'cost' : IDL.Float64,
          'expenses' : IDL.Float64,
          'profit' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getPurchaseBill' : IDL.Func([IDL.Text], [IDL.Opt(PurchaseBill)], ['query']),
  'getSaleInvoice' : IDL.Func([IDL.Text], [SaleInvoice], ['query']),
  'getSalesSummary' : IDL.Func(
      [Time, Time],
      [IDL.Record({ 'invoiceCount' : IDL.Nat, 'totalSales' : IDL.Float64 })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCreditNotes' : IDL.Func([], [IDL.Vec(CreditNote)], ['query']),
  'listDebitNotes' : IDL.Func([], [IDL.Vec(DebitNote)], ['query']),
  'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'listExpensesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'listInvoiceTemplates' : IDL.Func([], [IDL.Vec(InvoiceTemplate)], ['query']),
  'listParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPurchaseBills' : IDL.Func([], [IDL.Vec(PurchaseBill)], ['query']),
  'listPurchaseBillsByParty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PurchaseBill)],
      ['query'],
    ),
  'listSaleInvoices' : IDL.Func([], [IDL.Vec(SaleInvoice)], ['query']),
  'listSaleInvoicesByParty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SaleInvoice)],
      ['query'],
    ),
  'openPOSSession' : IDL.Func([POSSession], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDefaultTemplate' : IDL.Func([IDL.Text], [], []),
  'updateBalance' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateInvoiceTemplate' : IDL.Func([InvoiceTemplate], [], []),
  'updateParty' : IDL.Func([Party], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updatePurchaseBill' : IDL.Func([PurchaseBill], [], []),
  'updateSaleInvoice' : IDL.Func([SaleInvoice], [], []),
  'updateStock' : IDL.Func([IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CreditNote = IDL.Record({
    'id' : IDL.Text,
    'linkedInvoiceId' : IDL.Text,
    'date' : Time,
    'amount' : IDL.Float64,
    'partyId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const DebitNote = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'linkedBillId' : IDL.Text,
    'amount' : IDL.Float64,
    'partyId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'createdBy' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const InvoiceTemplate = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isDefault' : IDL.Bool,
    'printSize' : IDL.Variant({
      'a4' : IDL.Null,
      'a5' : IDL.Null,
      'thermal' : IDL.Null,
    }),
    'layoutConfig' : IDL.Text,
  });
  const Party = IDL.Record({
    'id' : IDL.Text,
    'currentBalance' : IDL.Float64,
    'kind' : IDL.Variant({ 'customer' : IDL.Null, 'vendor' : IDL.Null }),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'openingBalance' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'purchasePrice' : IDL.Float64,
    'lowStockThreshold' : IDL.Int,
    'stockQty' : IDL.Int,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'salePrice' : IDL.Float64,
  });
  const SaleInvoiceItem = IDL.Record({
    'qty' : IDL.Int,
    'productId' : IDL.Text,
    'discount' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const PurchaseBill = IDL.Record({
    'id' : IDL.Text,
    'tax' : IDL.Float64,
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'date' : Time,
    'billNumber' : IDL.Text,
    'paymentMode' : IDL.Text,
    'items' : IDL.Vec(SaleInvoiceItem),
    'paidAmount' : IDL.Float64,
    'partyId' : IDL.Text,
    'subtotal' : IDL.Float64,
  });
  const SaleInvoice = IDL.Record({
    'id' : IDL.Text,
    'tax' : IDL.Float64,
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'date' : Time,
    'createdBy' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'paymentMode' : IDL.Text,
    'items' : IDL.Vec(SaleInvoiceItem),
    'paidAmount' : IDL.Float64,
    'partyId' : IDL.Text,
    'subtotal' : IDL.Float64,
  });
  const AppRole = IDL.Variant({
    'Auditor' : IDL.Null,
    'Admin' : IDL.Null,
    'Manager' : IDL.Null,
    'Salesman' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'appRole' : AppRole, 'name' : IDL.Text });
  const POSSession = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'cashierId' : IDL.Text,
    'date' : Time,
    'openingCash' : IDL.Float64,
    'totalSales' : IDL.Float64,
    'closingCash' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearData' : IDL.Func([], [], []),
    'closePOSSession' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'createCreditNote' : IDL.Func([CreditNote], [], []),
    'createDebitNote' : IDL.Func([DebitNote], [], []),
    'createExpense' : IDL.Func([Expense], [], []),
    'createInvoiceTemplate' : IDL.Func([InvoiceTemplate], [], []),
    'createParty' : IDL.Func([Party], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'createPurchaseBill' : IDL.Func([PurchaseBill], [], []),
    'createSaleInvoice' : IDL.Func([SaleInvoice], [], []),
    'deleteParty' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentPOSSession' : IDL.Func([], [IDL.Opt(POSSession)], ['query']),
    'getDailySalesSummary' : IDL.Func(
        [Time],
        [IDL.Record({ 'invoiceCount' : IDL.Nat, 'totalSales' : IDL.Float64 })],
        ['query'],
      ),
    'getDefaultTemplate' : IDL.Func([], [IDL.Opt(InvoiceTemplate)], ['query']),
    'getExpenseSummary' : IDL.Func(
        [Time, Time],
        [IDL.Vec(IDL.Record({ 'total' : IDL.Float64, 'category' : IDL.Text }))],
        ['query'],
      ),
    'getInventoryReport' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'value' : IDL.Float64, 'product' : Product }))],
        ['query'],
      ),
    'getParty' : IDL.Func([IDL.Text], [IDL.Opt(Party)], ['query']),
    'getPartyLedger' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'invoices' : IDL.Vec(SaleInvoice),
            'bills' : IDL.Vec(PurchaseBill),
            'party' : IDL.Opt(Party),
          }),
        ],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProfitLoss' : IDL.Func(
        [Time, Time],
        [
          IDL.Record({
            'revenue' : IDL.Float64,
            'cost' : IDL.Float64,
            'expenses' : IDL.Float64,
            'profit' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getPurchaseBill' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PurchaseBill)],
        ['query'],
      ),
    'getSaleInvoice' : IDL.Func([IDL.Text], [SaleInvoice], ['query']),
    'getSalesSummary' : IDL.Func(
        [Time, Time],
        [IDL.Record({ 'invoiceCount' : IDL.Nat, 'totalSales' : IDL.Float64 })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCreditNotes' : IDL.Func([], [IDL.Vec(CreditNote)], ['query']),
    'listDebitNotes' : IDL.Func([], [IDL.Vec(DebitNote)], ['query']),
    'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'listExpensesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'listInvoiceTemplates' : IDL.Func(
        [],
        [IDL.Vec(InvoiceTemplate)],
        ['query'],
      ),
    'listParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPurchaseBills' : IDL.Func([], [IDL.Vec(PurchaseBill)], ['query']),
    'listPurchaseBillsByParty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PurchaseBill)],
        ['query'],
      ),
    'listSaleInvoices' : IDL.Func([], [IDL.Vec(SaleInvoice)], ['query']),
    'listSaleInvoicesByParty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SaleInvoice)],
        ['query'],
      ),
    'openPOSSession' : IDL.Func([POSSession], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDefaultTemplate' : IDL.Func([IDL.Text], [], []),
    'updateBalance' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateInvoiceTemplate' : IDL.Func([InvoiceTemplate], [], []),
    'updateParty' : IDL.Func([Party], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updatePurchaseBill' : IDL.Func([PurchaseBill], [], []),
    'updateSaleInvoice' : IDL.Func([SaleInvoice], [], []),
    'updateStock' : IDL.Func([IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };