/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface DebitNote {
    id: string;
    date: Time;
    linkedBillId: string;
    amount: number;
    partyId: string;
    reason: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Expense {
    id: string;
    date: Time;
    createdBy: string;
    description: string;
    category: string;
    amount: number;
}
export interface POSSession {
    id: string;
    status: string;
    cashierId: string;
    date: Time;
    openingCash: number;
    totalSales: number;
    closingCash: number;
}
export interface SaleInvoice {
    id: string;
    tax: number;
    status: string;
    total: number;
    date: Time;
    createdBy: string;
    invoiceNumber: string;
    paymentMode: string;
    items: Array<SaleInvoiceItem>;
    paidAmount: number;
    partyId: string;
    subtotal: number;
}
export interface Party {
    id: string;
    currentBalance: number;
    kind: Variant_customer_vendor;
    name: string;
    email: string;
    address: string;
    openingBalance: number;
    phone: string;
}
export interface CreditNote {
    id: string;
    linkedInvoiceId: string;
    date: Time;
    amount: number;
    partyId: string;
    reason: string;
}
export interface PurchaseBill {
    id: string;
    tax: number;
    status: string;
    total: number;
    date: Time;
    billNumber: string;
    paymentMode: string;
    items: Array<SaleInvoiceItem>;
    paidAmount: number;
    partyId: string;
    subtotal: number;
}
export interface InvoiceTemplate {
    id: string;
    name: string;
    isDefault: boolean;
    printSize: Variant_a4_a5_thermal;
    layoutConfig: string;
}
export interface SaleInvoiceItem {
    qty: bigint;
    productId: string;
    discount: number;
    price: number;
}
export interface Product {
    id: string;
    sku: string;
    purchasePrice: number;
    lowStockThreshold: bigint;
    stockQty: bigint;
    name: string;
    unit: string;
    isActive: boolean;
    category: string;
    salePrice: number;
}
export interface UserProfile {
    appRole: AppRole;
    name: string;
}
export enum AppRole {
    Auditor = "Auditor",
    Admin = "Admin",
    Manager = "Manager",
    Salesman = "Salesman"
}
export interface AppUser {
    username: string;
    name: string;
    appRole: AppRole;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_a4_a5_thermal {
    a4 = "a4",
    a5 = "a5",
    thermal = "thermal"
}
export enum Variant_customer_vendor {
    customer = "customer",
    vendor = "vendor"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearData(): Promise<void>;
    closePOSSession(id: string, closingCash: number): Promise<void>;
    createCreditNote(note: CreditNote): Promise<void>;
    createDebitNote(note: DebitNote): Promise<void>;
    createExpense(expense: Expense): Promise<void>;
    createInvoiceTemplate(template: InvoiceTemplate): Promise<void>;
    createParty(party: Party): Promise<void>;
    createProduct(product: Product): Promise<void>;
    createPurchaseBill(bill: PurchaseBill): Promise<void>;
    createSaleInvoice(invoice: SaleInvoice): Promise<void>;
    deleteParty(id: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentPOSSession(): Promise<POSSession | null>;
    getDailySalesSummary(date: Time): Promise<{
        invoiceCount: bigint;
        totalSales: number;
    }>;
    getDefaultTemplate(): Promise<InvoiceTemplate | null>;
    getExpenseSummary(startDate: Time, endDate: Time): Promise<Array<{
        total: number;
        category: string;
    }>>;
    getInventoryReport(): Promise<Array<{
        value: number;
        product: Product;
    }>>;
    getParty(id: string): Promise<Party | null>;
    getPartyLedger(partyId: string): Promise<{
        invoices: Array<SaleInvoice>;
        bills: Array<PurchaseBill>;
        party?: Party;
    }>;
    getProduct(id: string): Promise<Product>;
    getProfitLoss(startDate: Time, endDate: Time): Promise<{
        revenue: number;
        cost: number;
        expenses: number;
        profit: number;
    }>;
    getPurchaseBill(id: string): Promise<PurchaseBill | null>;
    getSaleInvoice(id: string): Promise<SaleInvoice>;
    getSalesSummary(startDate: Time, endDate: Time): Promise<{
        invoiceCount: bigint;
        totalSales: number;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFirstRun(): Promise<boolean>;
    loginWithPassword(username: string, password: string): Promise<{ name: string; appRole: AppRole } | null>;
    createAppUser(username: string, password: string, name: string, appRole: AppRole): Promise<boolean>;
    changeAppUserPassword(username: string, oldPassword: string, newPassword: string): Promise<boolean>;
    updateAppUser(username: string, name: string, appRole: AppRole): Promise<boolean>;
    deleteAppUser(username: string): Promise<boolean>;
    listAppUsers(): Promise<Array<AppUser>>;
    listCreditNotes(): Promise<Array<CreditNote>>;
    listDebitNotes(): Promise<Array<DebitNote>>;
    listExpenses(): Promise<Array<Expense>>;
    listExpensesByCategory(category: string): Promise<Array<Expense>>;
    listInvoiceTemplates(): Promise<Array<InvoiceTemplate>>;
    listParties(): Promise<Array<Party>>;
    listProducts(): Promise<Array<Product>>;
    listPurchaseBills(): Promise<Array<PurchaseBill>>;
    listPurchaseBillsByParty(partyId: string): Promise<Array<PurchaseBill>>;
    listSaleInvoices(): Promise<Array<SaleInvoice>>;
    listSaleInvoicesByParty(partyId: string): Promise<Array<SaleInvoice>>;
    openPOSSession(session: POSSession): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDefaultTemplate(id: string): Promise<void>;
    updateBalance(partyId: string, newBalance: number): Promise<void>;
    updateInvoiceTemplate(template: InvoiceTemplate): Promise<void>;
    updateParty(party: Party): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updatePurchaseBill(bill: PurchaseBill): Promise<void>;
    updateSaleInvoice(invoice: SaleInvoice): Promise<void>;
    updateStock(productId: string, newQty: bigint): Promise<void>;
}
import type { AppRole as _AppRole, InvoiceTemplate as _InvoiceTemplate, POSSession as _POSSession, Party as _Party, PurchaseBill as _PurchaseBill, SaleInvoice as _SaleInvoice, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearData();
            return result;
        }
    }
    async closePOSSession(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closePOSSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closePOSSession(arg0, arg1);
            return result;
        }
    }
    async createCreditNote(arg0: CreditNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCreditNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCreditNote(arg0);
            return result;
        }
    }
    async createDebitNote(arg0: DebitNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDebitNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDebitNote(arg0);
            return result;
        }
    }
    async createExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(arg0);
            return result;
        }
    }
    async createInvoiceTemplate(arg0: InvoiceTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoiceTemplate(to_candid_InvoiceTemplate_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoiceTemplate(to_candid_InvoiceTemplate_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createParty(arg0: Party): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createParty(to_candid_Party_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createParty(to_candid_Party_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async createPurchaseBill(arg0: PurchaseBill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseBill(arg0);
            return result;
        }
    }
    async createSaleInvoice(arg0: SaleInvoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSaleInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSaleInvoice(arg0);
            return result;
        }
    }
    async deleteParty(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParty(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentPOSSession(): Promise<POSSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentPOSSession();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentPOSSession();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailySalesSummary(arg0: Time): Promise<{
        invoiceCount: bigint;
        totalSales: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySalesSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySalesSummary(arg0);
            return result;
        }
    }
    async getDefaultTemplate(): Promise<InvoiceTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultTemplate();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultTemplate();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseSummary(arg0: Time, arg1: Time): Promise<Array<{
        total: number;
        category: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseSummary(arg0, arg1);
            return result;
        }
    }
    async getInventoryReport(): Promise<Array<{
        value: number;
        product: Product;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryReport();
            return result;
        }
    }
    async getParty(arg0: string): Promise<Party | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParty(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParty(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartyLedger(arg0: string): Promise<{
        invoices: Array<SaleInvoice>;
        bills: Array<PurchaseBill>;
        party?: Party;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartyLedger(arg0);
                return from_candid_record_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartyLedger(arg0);
            return from_candid_record_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return result;
        }
    }
    async getProfitLoss(arg0: Time, arg1: Time): Promise<{
        revenue: number;
        cost: number;
        expenses: number;
        profit: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitLoss(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitLoss(arg0, arg1);
            return result;
        }
    }
    async getPurchaseBill(arg0: string): Promise<PurchaseBill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseBill(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseBill(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaleInvoice(arg0: string): Promise<SaleInvoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaleInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaleInvoice(arg0);
            return result;
        }
    }
    async getSalesSummary(arg0: Time, arg1: Time): Promise<{
        invoiceCount: bigint;
        totalSales: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesSummary(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCreditNotes(): Promise<Array<CreditNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCreditNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCreditNotes();
            return result;
        }
    }
    async listDebitNotes(): Promise<Array<DebitNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDebitNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDebitNotes();
            return result;
        }
    }
    async listExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses();
            return result;
        }
    }
    async listExpensesByCategory(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpensesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpensesByCategory(arg0);
            return result;
        }
    }
    async listInvoiceTemplates(): Promise<Array<InvoiceTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoiceTemplates();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoiceTemplates();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listParties(): Promise<Array<Party>> {
        if (this.processError) {
            try {
                const result = await this.actor.listParties();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listParties();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return result;
        }
    }
    async listPurchaseBills(): Promise<Array<PurchaseBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPurchaseBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPurchaseBills();
            return result;
        }
    }
    async listPurchaseBillsByParty(arg0: string): Promise<Array<PurchaseBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPurchaseBillsByParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPurchaseBillsByParty(arg0);
            return result;
        }
    }
    async listSaleInvoices(): Promise<Array<SaleInvoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSaleInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSaleInvoices();
            return result;
        }
    }
    async listSaleInvoicesByParty(arg0: string): Promise<Array<SaleInvoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSaleInvoicesByParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSaleInvoicesByParty(arg0);
            return result;
        }
    }
    async openPOSSession(arg0: POSSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.openPOSSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openPOSSession(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDefaultTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultTemplate(arg0);
            return result;
        }
    }
    async updateBalance(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBalance(arg0, arg1);
            return result;
        }
    }
    async updateInvoiceTemplate(arg0: InvoiceTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceTemplate(to_candid_InvoiceTemplate_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceTemplate(to_candid_InvoiceTemplate_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateParty(arg0: Party): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(to_candid_Party_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(to_candid_Party_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async updatePurchaseBill(arg0: PurchaseBill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseBill(arg0);
            return result;
        }
    }
    async updateSaleInvoice(arg0: SaleInvoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSaleInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSaleInvoice(arg0);
            return result;
        }
    }
    async updateStock(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStock(arg0, arg1);
            return result;
        }
    }

    async isFirstRun(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFirstRun();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFirstRun();
            return result;
        }
    }
    async loginWithPassword(arg0: string, arg1: string): Promise<{ name: string; appRole: AppRole } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithPassword(arg0, arg1);
                return result.length === 0 ? null : { name: result[0].name, appRole: from_candid_AppRole_n19(this._uploadFile, this._downloadFile, result[0].appRole) };
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithPassword(arg0, arg1);
            return result.length === 0 ? null : { name: result[0].name, appRole: from_candid_AppRole_n19(this._uploadFile, this._downloadFile, result[0].appRole) };
        }
    }
    async createAppUser(arg0: string, arg1: string, arg2: string, arg3: AppRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppUser(arg0, arg1, arg2, to_candid_AppRole_n38(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppUser(arg0, arg1, arg2, to_candid_AppRole_n38(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async changeAppUserPassword(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAppUserPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAppUserPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAppUser(arg0: string, arg1: string, arg2: AppRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppUser(arg0, arg1, to_candid_AppRole_n38(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppUser(arg0, arg1, to_candid_AppRole_n38(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteAppUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppUser(arg0);
            return result;
        }
    }
    async listAppUsers(): Promise<Array<AppUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppUsers();
                return result.map((u: any) => ({ username: u.username, name: u.name, appRole: from_candid_AppRole_n19(this._uploadFile, this._downloadFile, u.appRole) }));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppUsers();
            return result.map((u: any) => ({ username: u.username, name: u.name, appRole: from_candid_AppRole_n19(this._uploadFile, this._downloadFile, u.appRole) }));
        }
    }
}

function from_candid_AppRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceTemplate_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceTemplate): InvoiceTemplate {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Party_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Party): Party {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_POSSession]): POSSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceTemplate]): InvoiceTemplate | null {
    return value.length === 0 ? null : from_candid_InvoiceTemplate_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Party]): Party | null {
    return value.length === 0 ? null : from_candid_Party_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PurchaseBill]): PurchaseBill | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _AppRole;
    name: string;
}): {
    appRole: AppRole;
    name: string;
} {
    return {
        appRole: from_candid_AppRole_n19(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    isDefault: boolean;
    printSize: {
        a4: null;
    } | {
        a5: null;
    } | {
        thermal: null;
    };
    layoutConfig: string;
}): {
    id: string;
    name: string;
    isDefault: boolean;
    printSize: Variant_a4_a5_thermal;
    layoutConfig: string;
} {
    return {
        id: value.id,
        name: value.name,
        isDefault: value.isDefault,
        printSize: from_candid_variant_n27(_uploadFile, _downloadFile, value.printSize),
        layoutConfig: value.layoutConfig
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    currentBalance: number;
    kind: {
        customer: null;
    } | {
        vendor: null;
    };
    name: string;
    email: string;
    address: string;
    openingBalance: number;
    phone: string;
}): {
    id: string;
    currentBalance: number;
    kind: Variant_customer_vendor;
    name: string;
    email: string;
    address: string;
    openingBalance: number;
    phone: string;
} {
    return {
        id: value.id,
        currentBalance: value.currentBalance,
        kind: from_candid_variant_n31(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        email: value.email,
        address: value.address,
        openingBalance: value.openingBalance,
        phone: value.phone
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invoices: Array<_SaleInvoice>;
    bills: Array<_PurchaseBill>;
    party: [] | [_Party];
}): {
    invoices: Array<SaleInvoice>;
    bills: Array<PurchaseBill>;
    party?: Party;
} {
    return {
        invoices: value.invoices,
        bills: value.bills,
        party: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.party))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Auditor: null;
} | {
    Admin: null;
} | {
    Manager: null;
} | {
    Salesman: null;
}): AppRole {
    return "Auditor" in value ? AppRole.Auditor : "Admin" in value ? AppRole.Admin : "Manager" in value ? AppRole.Manager : "Salesman" in value ? AppRole.Salesman : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    a4: null;
} | {
    a5: null;
} | {
    thermal: null;
}): Variant_a4_a5_thermal {
    return "a4" in value ? Variant_a4_a5_thermal.a4 : "a5" in value ? Variant_a4_a5_thermal.a5 : "thermal" in value ? Variant_a4_a5_thermal.thermal : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    vendor: null;
}): Variant_customer_vendor {
    return "customer" in value ? Variant_customer_vendor.customer : "vendor" in value ? Variant_customer_vendor.vendor : value;
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceTemplate>): Array<InvoiceTemplate> {
    return value.map((x)=>from_candid_InvoiceTemplate_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Party>): Array<Party> {
    return value.map((x)=>from_candid_Party_n29(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceTemplate_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceTemplate): _InvoiceTemplate {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Party_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Party): _Party {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    isDefault: boolean;
    printSize: Variant_a4_a5_thermal;
    layoutConfig: string;
}): {
    id: string;
    name: string;
    isDefault: boolean;
    printSize: {
        a4: null;
    } | {
        a5: null;
    } | {
        thermal: null;
    };
    layoutConfig: string;
} {
    return {
        id: value.id,
        name: value.name,
        isDefault: value.isDefault,
        printSize: to_candid_variant_n12(_uploadFile, _downloadFile, value.printSize),
        layoutConfig: value.layoutConfig
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    currentBalance: number;
    kind: Variant_customer_vendor;
    name: string;
    email: string;
    address: string;
    openingBalance: number;
    phone: string;
}): {
    id: string;
    currentBalance: number;
    kind: {
        customer: null;
    } | {
        vendor: null;
    };
    name: string;
    email: string;
    address: string;
    openingBalance: number;
    phone: string;
} {
    return {
        id: value.id,
        currentBalance: value.currentBalance,
        kind: to_candid_variant_n15(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        email: value.email,
        address: value.address,
        openingBalance: value.openingBalance,
        phone: value.phone
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: AppRole;
    name: string;
}): {
    appRole: _AppRole;
    name: string;
} {
    return {
        appRole: to_candid_AppRole_n38(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_a4_a5_thermal): {
    a4: null;
} | {
    a5: null;
} | {
    thermal: null;
} {
    return value == Variant_a4_a5_thermal.a4 ? {
        a4: null
    } : value == Variant_a4_a5_thermal.a5 ? {
        a5: null
    } : value == Variant_a4_a5_thermal.thermal ? {
        thermal: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_customer_vendor): {
    customer: null;
} | {
    vendor: null;
} {
    return value == Variant_customer_vendor.customer ? {
        customer: null
    } : value == Variant_customer_vendor.vendor ? {
        vendor: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Auditor: null;
} | {
    Admin: null;
} | {
    Manager: null;
} | {
    Salesman: null;
} {
    return value == AppRole.Auditor ? {
        Auditor: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value == AppRole.Manager ? {
        Manager: null
    } : value == AppRole.Salesman ? {
        Salesman: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
